Repository redBorder/cookbook-pmacct, pull requests merged in 2024-06, with the labels that each got.

#6 create pmacct dir
  resources/providers/config.rb
Labels: size/XS, kind/feature

#7 Release 0.0.5
  CHANGELOG.md
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
Labels: release

#8 Improvement/fix lint
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: enhancement, kind/bug, linter, refactor, size/L

#9 Release 0.0.6
  CHANGELOG.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: kind/documentation, size/L
